import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./../styles/globals.css";
import MainNavbar from './../components/main-navbar/main-navbar';
import { Toaster } from "@/components/ui/toaster"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainNavbar></MainNavbar>
          {children}
        <Toaster/>
      </body>
    </html>
  );
}
